2021-07-29 10:44:30,063 ERROR: Exception on /index [GET] [in g:\intercloud\flask\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\intercloud\flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "g:\intercloud\flask\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "G:\Intercloud\flask\microblog\app\routes.py", line 33, in index
    return render_template('index.html',posts=posts.items,title="Home Page",form=form,next_url=next_url,prev_url=prev_url)
  File "g:\intercloud\flask\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "g:\intercloud\flask\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "g:\intercloud\flask\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "g:\intercloud\flask\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "g:\intercloud\flask\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "G:\Intercloud\flask\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "G:\Intercloud\flask\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "g:\intercloud\flask\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "g:\intercloud\flask\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "g:\intercloud\flask\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "g:\intercloud\flask\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "G:\Intercloud\flask\microblog\app\templates\base.html", line 29, in block "content"
    {% block app_content %}{% endblock %}
  File "G:\Intercloud\flask\microblog\app\templates\index.html", line 19, in block "app_content"
    {% include '_post.html' %}
  File "G:\Intercloud\flask\microblog\app\templates\_post.html", line 10, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
  File "g:\intercloud\flask\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "g:\intercloud\flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "g:\intercloud\flask\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "g:\intercloud\flask\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'register' instead?
2021-07-29 10:45:25,454 INFO: Microblog Startup [in G:\Intercloud\flask\microblog\app\__init__.py:40]
2021-07-29 10:58:00,916 INFO: Microblog Startup [in G:\Intercloud\flask\microblog\app\__init__.py:40]
2021-07-29 11:00:29,256 INFO: Microblog Startup [in G:\Intercloud\flask\microblog\app\__init__.py:40]
2021-07-29 11:00:37,231 ERROR: Exception on / [GET] [in g:\intercloud\flask\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\intercloud\flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\intercloud\flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "g:\intercloud\flask\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "G:\Intercloud\flask\microblog\app\routes.py", line 33, in index
    return render_template('index.html',posts=posts.items,title="Home Page",form=form,next_url=next_url,prev_url=prev_url)
  File "g:\intercloud\flask\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "g:\intercloud\flask\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "g:\intercloud\flask\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "g:\intercloud\flask\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "g:\intercloud\flask\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "G:\Intercloud\flask\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "g:\intercloud\flask\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "g:\intercloud\flask\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "G:\Intercloud\flask\microblog\app\templates\base.html", line 13, in template
    {% block navbar %}
jinja2.exceptions.TemplateAssertionError: block 'navbar' defined twice
2021-07-29 11:00:57,584 INFO: Microblog Startup [in G:\Intercloud\flask\microblog\app\__init__.py:40]
2021-07-29 11:08:02,306 INFO: Microblog Startup [in G:\Intercloud\flask\microblog\app\__init__.py:40]
2021-07-29 11:08:26,290 INFO: Microblog Startup [in G:\Intercloud\flask\microblog\app\__init__.py:40]
2021-07-29 11:08:54,054 INFO: Microblog Startup [in G:\Intercloud\flask\microblog\app\__init__.py:40]
2021-07-29 11:09:41,973 INFO: Microblog Startup [in G:\Intercloud\flask\microblog\app\__init__.py:40]
2021-07-29 11:09:59,733 INFO: Microblog Startup [in G:\Intercloud\flask\microblog\app\__init__.py:40]
2021-07-29 11:15:13,004 INFO: Microblog Startup [in G:\Intercloud\flask\microblog\app\__init__.py:40]
2021-07-29 11:15:20,329 INFO: Microblog Startup [in G:\Intercloud\flask\microblog\app\__init__.py:40]
2021-07-29 12:23:27,167 INFO: Microblog startup [in G:\Intercloud\flask\microblog\app\__init__.py:77]
